version: '3'
services:
  devoper_nginx:
    image: nginx:latest
    container_name: devoper_nginx_proxy
    depends_on: 
      - devoper
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    ports:
      - '443:443'
  devoper:
    build: .
    container_name: devoper
    command: python main.py